In [1]:
import numpy as np

# Creating Arrays

In [2]:
a = np.array([1,2,3])

In [3]:
print(a)

[1 2 3]


In [6]:
b = np.array([(1,2,3), (4,5,6)], dtype=float)

In [7]:
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [8]:
c = np.array([[(1,2,3),(4,5,6)], [(7,8,9), (1,2,3)]])

In [9]:
print(c)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]


## Inspecting Your Array

In [12]:
a.shape



(2, 3)

In [13]:
b.shape

(2, 3)

In [14]:
c.shape

(2, 2, 3)

In [15]:
len(a)

3

In [16]:
len(c)

2

In [17]:
a.dtype

dtype('int32')

In [18]:
b.dtype

dtype('float64')

# Asking for Help

In [19]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# Array Mathematics

In [20]:
g = a - b

In [21]:
print(g)

[[ 0.  0.  0.]
 [-3. -3. -3.]]


In [22]:
f = a + b

In [23]:
print(f)

[[2. 4. 6.]
 [5. 7. 9.]]


In [24]:
h = a / b

In [25]:
print(h)

[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]


In [26]:
i = np.multiply(a,b)

In [27]:
print(i)

[[ 1.  4.  9.]
 [ 4. 10. 18.]]


# Comparison

In [28]:
print ( a == b)

[[ True  True  True]
 [False False False]]


# Subsetting, Slicing , Indexing

## Subsetting

In [29]:
print(a[2])

3


In [30]:
print(b[1,2])

6.0


## Slicing

In [53]:
x = np.array([[(1,2,3)], [(4,5,6)], [(7,8,9)]])

In [55]:
x.shape
x

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

In [88]:
x[0:3,0:3,0:3]

array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]])

# Array Manupilation

## Transposing an Array

In [95]:
x = np.array([[(1,2,3)], [(4,5,6)]])
x

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [96]:
y = np.transpose(x)

In [97]:
y

array([[[1, 4]],

       [[2, 5]],

       [[3, 6]]])

## Changing Array Shape

In [100]:
y = x.reshape(1,6)

In [101]:
y

array([[1, 2, 3, 4, 5, 6]])

## Combining Arrays

In [103]:
a = np.asarray([(1,2),(3,4)])
b = np.asarray([(4,5),(6,7)])

In [105]:
c = np.concatenate((a,b), axis=0)

In [106]:
c

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [107]:
d = np.concatenate((a,b), axis=1)

In [108]:
d

array([[1, 2, 4, 5],
       [3, 4, 6, 7]])